graph LR
pick_representatives --> argmin_vecnorm
pick_representatives --> must_have
pick_representatives --> tie_break
pick_representatives --> name2idx
pick_representatives --> getdef
tie_break --> argmin_vecnorm
